# Unique name for this workflow
name: BUILD on PR

# Definition when the workflow should run
on:
    pull_request:
        types: [opened, edited, synchronize, reopened]
    push:
        branches:
        - total040-actions-demo-1

# Workflow environment variables
##env:
    # Is the PR base branch a prerelease branch
##    IS_PRERELEASE: ${{ startsWith(github.event.pull_request.base.ref, 'prerelease/') || inputs.prerelease  }}

# Jobs to be executed
jobs:
    # Dummy job used to skip CI run on automated PRs
    skip-ci:
        if: github.actor == 'trailheadapps-bot'
        runs-on: ubuntu-latest
        steps:
            - name: Noop
              run: |
                  echo "Skipping CI run for automated PRs."

    # Formatting and linting only runs on human-submitted PRs
    format-lint-lwc-tests:
        if: github.actor != 'trailheadapps-bot'
        runs-on: ubuntu-latest
        steps:
            # Checkout the source code
            - name: 'Checkout source code'
              uses: actions/checkout@v4

            # Install Volta to enforce proper node and package manager versions
            - name: 'Install Volta'
              uses: volta-cli/action@v4

            # Cache node_modules to speed up the process
            - name: 'Restore node_modules cache'
              id: cache-npm
              uses: actions/cache@v4
              with:
                  path: node_modules
                  key: npm-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      npm-${{ env.cache-name }}-
                      npm-

            # Install npm dependencies for Prettier and Jest
            - name: 'Install npm dependencies'
              if: steps.cache-npm.outputs.cache-hit != 'true'
              run: | 
               npm install 
               HUSKY=0 npm ci

            # Prettier formatting
            - name: 'Code formatting verification with Prettier'
              run: npm run prettier:verify

            # Lint LWC / Aura
            - name: 'Lint Lightning Web Components / Aura Components'
              run: npm run lint

            # LWC unit tests
            - name: 'Unit test Lightning Web Components'
              run: npm run test:unit:coverage

            # Upload code coverage data
            - name: 'Upload code coverage for LWC to Codecov.io'
              uses: codecov/codecov-action@v4
              with:
                  token: ${{ secrets.CODECOV_TOKEN }}
                  flags: LWC

    # Auto merge Dependabot PRs for:
    # - patch updates on prod dependencies
    # - minor updates on dev dependencies
    dependabot-auto-merge:
        # Only run for Dependabot PRs
        if: github.actor == 'dependabot[bot]'
        runs-on: ubuntu-latest
        needs: format-lint-lwc-tests
        permissions:
            pull-requests: write
            contents: write
        steps:
            - name: 'Fetch Dependabot metadata'
              id: dependabot
              uses: dependabot/fetch-metadata@v2

            - name: 'Check auto merge conditions'
              id: auto-merge
              if: |
                  (
                    steps.dependabot.outputs.update-type == 'version-update:semver-patch' &&
                    contains('direct:production,indirect:production', steps.dependabot.outputs.dependency-type)
                  ) || (
                    contains('version-update:semver-minor,version-update:semver-patch', steps.dependabot.outputs.update-type) &&
                    contains('direct:development,indirect:development', steps.dependabot.outputs.dependency-type)
                  )
              run: echo "::notice ::auto-merge conditions satisfied"

            - name: 'Approve and merge PR'
              if: steps.auto-merge.conclusion == 'success'
              run: |
                  gh pr review --approve "$PR_URL"
                  gh pr merge --auto --rebase "$PR_URL"
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  PR_URL: ${{ github.event.pull_request.html_url }}

    pr-test:
        runs-on: ubuntu-latest
        needs: format-lint-lwc-tests
        if: github.actor != 'dependabot[bot]'
        steps:
            # Checkout the source code
            - name: 'Checkout source code'
              uses: actions/checkout@v4

            # Run PMD scan
            - name: 'Run PMD scan'
              uses: pmd/pmd-github-action@v2.0.0
              id: pmd
              with:
                  version: '6.55.0'
                  sourcePath: 'force-app'
                  rulesets: 'ruleset.xml'

            # Check for PMD violations
            - name: 'Check for PMD violations'
              if: steps.pmd.outputs.violations != 0
              run: exit 1

            # Install Salesforce CLI
            - name: 'Install Salesforce CLI'
              run: |
                  npm install @salesforce/cli --location=global
                  nodeInstallPath=$(npm config get prefix)
                  echo "$nodeInstallPath/bin" >> $GITHUB_PATH
                  sf --version

            # Store secret for dev hub
            - name: 'Populate auth file with ORG_SFDX_URL secret'
              shell: bash
              run: |
                  echo ${{ secrets.ORG_SFDX_URL }} > ./ORG_SFDX_URL.txt
                  secretFileSize=$(wc -c "./ORG_SFDX_URL.txt" | awk '{print $1}')
                  if [ $secretFileSize == 1 ]; then
                      echo "Missing ORG_SFDX_URL secret. Is this workflow running on a fork?";
                      exit 1;
                  fi

            # Authenticate target org
            - name: 'Authenticate Dev Hub'
              run: sf org login sfdx-url -f ./ORG_SFDX_URL.txt -a target_org -s

            # Query some data
            - name: 'query accounts from target org'
              run: sf data query --query "SELECT Id, Name FROM Account LIMIT 2

            # Run Apex tests in scratch org
            - name: 'Run Apex tests'
              run: sf apex test run -c -r human -d ./tests/apex -w 20